spring:
  application:
    name: hub
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${HUB_SERVER_DB_URL}
    username: ${HUB_SERVER_DB_USERNAME}
    password: ${HUB_SERVER_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${HUB_SERVER_PORT}

springdoc:
  api-docs:
    path: /hubs/v3/api-docs
  swagger-ui:
    path: /hubs/swagger-ui.html

eureka:
  instance:
    hostname: ${HUB_SERVER_HOST}
  client:
    service-url:
      defaultZone: "${EUREKA_SERVER_URL}"
    register-with-eureka: true  # Eureka 서버에 등록
    fetch-registry: true  # Eureka 서버로부터 레지스트리 정보 가져오기