spring:
  application:
    name: hub
  config:
    activate:
      on-profile: local
  datasource:
    url: ${HUB_SERVER_DB_URL}
    username: ${HUB_SERVER_DB_USERNAME}
    password: ${HUB_SERVER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
#    driver-class-name: org.h2.Driver
#    url: 'jdbc:h2:mem:test'
#    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${HUB_SERVER_PORT}

eureka:
  instance:
    hostname: ${HUB_SERVER_HOST}
  client:
    service-url:
      defaultZone: "${EUREKA_SERVER_URL}"
    register-with-eureka: true  # Eureka 서버에 등록
    fetch-registry: true  # Eureka 서버로부터 레지스트리 정보 가져오기