spring:
  application:
    name: order
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://${ORDER_SERVER_DB_CONTAINER_NAME}:${ORDER_SERVER_DB_PORT}/${ORDER_SERVER_DB_NAME}
    username: ${ORDER_SERVER_DB_USERNAME}
    password: ${ORDER_SERVER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${ORDER_SERVER_PORT}

springdoc:
  api-docs:
    path: /orders/v3/api-docs
  swagger-ui:
    path: /orders/swagger-ui.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

eureka:
  instance:
    hostname: ${ORDER_SERVER_CONTAINER_NAME}
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_CONTAINER_NAME}:${EUREKA_SERVER_PORT}/eureka/
    register-with-eureka: true  # Eureka 서버에 등록
    fetch-registry: true  # Eureka 서버로부터 레지스트리 정보 가져오기