spring:
  application:
    name: order
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${ORDER_SERVER_DB_URL}
    username: ${ORDER_SERVER_DB_USERNAME}
    password: ${ORDER_SERVER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${ORDER_SERVER_PORT}

eureka:
  instance:
    hostname: ${ORDER_SERVER_HOST}
  client:
    service-url:
      defaultZone: "${EUREKA_SERVER_URL}"
    register-with-eureka: true  # Eureka 서버에 등록
    fetch-registry: true  # Eureka 서버로부터 레지스트리 정보 가져오기