spring:
  application:
    name: company
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: ${ORDER_SERVER_PORT}

eureka:
  instance:
    hostname: ${ORDER_SERVER_HOST}
  client:
    service-url:
      defaultZone: "${EUREKA_SERVER_URL}"
    register-with-eureka: true  # Eureka 서버에 등록
    fetch-registry: true  # Eureka 서버로부터 레지스트리 정보 가져오기