spring:
  application:
    name: gateway
  config:
    activate:
      on-profile: dev
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/api/users/**, /api/auth/**, /users/v3/api-docs

        - id: company
          uri: lb://company
          predicates:
            - Path=/api/companies/**, /api/products/**, /companies/v3/api-docs

        - id: hub
          uri: lb://hub
          predicates:
            - Path=/api/hubs/**, /api/hub-routes/**, /api/delivery-managers/**, /hubs/v3/api-docs

        - id: order
          uri: lb://order
          predicates:
              - Path=/api/deliveries/**, /api/orders/**, /api/delivery-histories/**, /orders/v3/api-docs

server:
  port: ${GATEWAY_SERVER_PORT}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - url: /users/v3/api-docs
        name: User
      - url: /companies/v3/api-docs
        name: Company
      - url: /hubs/v3/api-docs
        name: Hub
      - url: /orders/v3/api-docs
        name: Order

eureka:
  instance:
    hostname: ${GATEWAY_SERVER_CONTAINER_NAME}
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_CONTAINER_NAME}:${EUREKA_SERVER_PORT}/eureka/
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret-key: ${JWT_SECRET_KEY}