spring:
  application:
    name: gateway
  config:
    activate:
      on-profile: local
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://${USER_SERVER_HOST}:${USER_SERVER_PORT}
          predicates:
            - Path=/api/users/**, /api/auth/**, /users/v3/api-docs

        - id: company
          uri: http://${COMPANY_SERVER_HOST}:${COMPANY_SERVER_PORT}
          predicates:
            - Path=/api/companies/**, /api/products/**, /companies/v3/api-docs

        - id: hub
          uri: http://${HUB_SERVER_HOST}:${HUB_SERVER_HOST}
          predicates:
            - Path=/api/hubs/**, /api/hub-routes/**, /hubs/v3/api-docs

        - id: order
          uri: http://${ORDER_SERVER_HOST}:${ORDER_SERVER_HOST}
          predicates:
            - Path=/api/deliveries/**, /api/orders/**, /orders/v3/api-docs

server:
  port: ${GATEWAY_SERVER_PORT}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - url: /users/v3/api-docs
        name: User
      - url: /companies/v3/api-docs
        name: Company
      - url: /hubs/v3/api-docs
        name: Hub
      - url: /orders/v3/api-docs
        name: Order

eureka:
  instance:
    hostname: ${GATEWAY_SERVER_HOST}
  client:
    service-url:
      defaultZone: "${EUREKA_SERVER_URL}"
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret-key: ${JWT_SECRET_KEY}