services:
  eureka-app:
    container_name: eureka-app
    build:
      context: ../eureka
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${EUREKA_SERVER_PORT}:${EUREKA_SERVER_PORT}"
    networks:
      - delivery-msa-net
    environment:
      EUREKA_SERVER_PORT: ${EUREKA_SERVER_PORT}
      EUREKA_SERVER_HOST: ${EUREKA_SERVER_HOST}

networks:
  delivery-msa-net:
    external: true