services:
  eureka-app:
    container_name: eureka-app
    build:
      context: ../eureka
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${EUREKA_SERVER_PORT}:${EUREKA_SERVER_PORT}"
    networks:
      - external-network
      - internal-network
    environment:
      EUREKA_SERVER_PORT: ${EUREKA_SERVER_PORT}
      EUREKA_SERVER_HOST: ${EUREKA_SERVER_HOST}

networks:
  external-network:
    external: true
  internal-network:
    external: true