services:
  gateway-app:
    container_name: gateway-app
    build:
      context: ../gateway
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${GATEWAY_SERVER_PORT}:${GATEWAY_SERVER_PORT}"
    networks:
      - external-network
      - internal-network
      - monitoring-network
    environment:

      # gateway 관련
      GATEWAY_SERVER_PORT: ${GATEWAY_SERVER_PORT}
      GATEWAY_SERVER_CONTAINER_NAME: ${GATEWAY_SERVER_CONTAINER_NAME}
      GATEWAY_SERVER_HOST: ${GATEWAY_SERVER_HOST}

      # eureka 관련
      EUREKA_SERVER_CONTAINER_NAME: ${EUREKA_SERVER_CONTAINER_NAME}
      EUREKA_SERVER_PORT: ${EUREKA_SERVER_PORT}

      # zipkin 관련
      ZIPKIN_PORT: ${ZIPKIN_PORT}
      ZIPKIN_HOST: ${ZIPKIN_HOST}
      ZIPKIN_CONTAINER_NAME: ${ZIPKIN_CONTAINER_NAME}

      # 기타 환경 변수 관련
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

networks:
  external-network:
    external: true
  internal-network:
    external: true
  monitoring-network:
    external: true