services:
  user-db:
    image: postgres:16.4
    container_name: user-db
    environment:
      POSTGRES_USER: ${USER_SERVER_DB_USERNAME}
      POSTGRES_PASSWORD: ${USER_SERVER_DB_PASSWORD}
      POSTGRES_DB: ${USER_SERVER_DB_NAME}
    ports:
      - "${USER_SERVER_DB_PORT}:${USER_SERVER_DB_PORT}"
    volumes:
      - postgres-data:${USER_SERVER_DB_VOLUMES}
    networks:
      - service-network

  user-app:
    container_name: user-app
    build:
      context: ../user
      dockerfile: Dockerfile
    depends_on:
      - user-db
    restart: always
    ports:
      - "${USER_SERVER_PORT}:${USER_SERVER_PORT}"
    networks:
      - service-network
    environment:
      SPRING_DATASOURCE_URL: ${USER_SERVER_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${USER_SERVER_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${USER_SERVER_DB_PASSWORD}
      USER_SERVER_PORT: ${USER_SERVER_PORT}
      USER_SERVER_HOST: ${USER_SERVER_HOST}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
      GATEWAY_SERVER_HOST: ${GATEWAY_SERVER_HOST}
      GATEWAY_SERVER_PORT: ${GATEWAY_SERVER_PORT}

networks:
  service-network:
    external: true

volumes:
  postgres-data: