spring:
  application:
    name: eureka

server:
  port: ${EUREKA_PORT}

eureka:
  instance:
    hostname: ${EUREKA_HOST}
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false